#!/usr/bin/env python3
#placeholder http server to have something to test against

import sys, os, socket
from socketserver import ThreadingMixIn
from http.server import SimpleHTTPRequestHandler, HTTPServer

HOST = socket.gethostname()

class ThreadingSimpleServer(ThreadingMixIn, HTTPServer):
    address_family = socket.AF_INET6
    pass

PORT = int(os.getenv('REPLAYD_PORT', 8080))
CWD = os.getenv('REPLAYD_ROOT','/var/tmp')

os.chdir(CWD)

server = ThreadingSimpleServer(('::', PORT), SimpleHTTPRequestHandler)
print("Serving HTTP traffic from", CWD, "on", HOST, "using port", PORT)
try:
    while 1:
        sys.stdout.flush()
        server.handle_request()
except KeyboardInterrupt:
    print("\nShutting down")

# vim: set et ai ts=4 sw=4 tw=0 ft=python: #
